// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKD3vO63jwOjREPcElfkUiu73NPJ-qq5Q',
    appId: '1:268911879517:android:67f1d746011f94eca774b4',
    messagingSenderId: '268911879517',
    projectId: 'social-login-flutter-b022e',
    storageBucket: 'social-login-flutter-b022e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBNvcT3yTDJngSdGNsTd7WqZzc1JUbgA',
    appId: '1:268911879517:ios:988c487d44605b23a774b4',
    messagingSenderId: '268911879517',
    projectId: 'social-login-flutter-b022e',
    storageBucket: 'social-login-flutter-b022e.appspot.com',
    androidClientId: '268911879517-0g6ttt2nmug4gpuv84b3a2qu1ejk4s03.apps.googleusercontent.com',
    iosClientId: '268911879517-ljht8ihdqb80p71cpindv7lst97g2nf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLoginFirebase',
  );
}
